### ISSUE TITLE
JSON not created safely

### ISSUE THREAD

**Issue by hansottowirtz** [jonasbostoen/bxgateway#1]
The JSON is created by string interpolation, but this is not safe when using untrusted input.

e.g. if topic is `ab"cd`, the JSON will be invalid:
https://github.com/jonasbostoen/bxgateway/blob/809badd9304245260ff879c2320b11821cb5efbf/src/bxgateway.ts#L73

I would recommend creating a JS object first and then using `JSON.stringify`.

**Comment by mempirate** [comment]
Fixed in 246b1c796acc4964aa80893ae404c17536ba7f5d
